name: Sync Repos Action
description: An automated GitHub Action to sync files or directories across multiple repositories.

inputs:
  target-repo:
    description: The GitHub repository where the files or directories need to be updated.
    required: true
  target-path:
    description: Path of the target file or directory in the target repository where the changes need to be reflected. It can be a file or a directory.
    required: true
  source-path:
    description: Local path of the file or directory that contains the changes to be propagated. It can be a file or a directory.
    required: true
  branch-name:
    description: Name of the new branch to be created for the changes.
    required: true
  github-token:
    description: A GitHub token with appropriate permissions to create and manage PRs.
    required: true
  commit-message:
    description: Message for the commit that includes the changes.
    required: true
  base-branch:
    description: The branch that the changes should be based off of. If not provided, defaults to 'main'.
    required: false
    default: main
  label:
    description: Labels to be applied to the PR for better categorization. Defaults to 'documentation' if not provided.
    required: false
    default: documentation
  user-email:
    description: The email address associated with the GitHub account performing the action. This will be used to associate the commits and pull request with this user.
    required: true
  user-name:
    description: The username of the GitHub account performing the action. This will be reflected in the commits and pull request.
    required: true
   
runs:
  using: composite
  steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          source-path:
            - "${{ inputs.source-path }}"
    - name: "Sync Files/Directories"
      if: steps.filter.outputs.source-path == 'true'
      run : |
          git config --global user.email "${{ inputs.user-email }}"
          git config --global user.name "${{ inputs.user-name }}"
          git clone --branch ${{ inputs.base-branch }} https://${{ inputs.github-token }}@github.com/${{ inputs.target-repo }}.git temp
          cp -r ${{ inputs.source-path }} temp/${{ inputs.target-path }}
          cd temp
          git remote set-url origin https://x-access-token:${{ inputs.github-token }}@github.com/${{ inputs.target-repo }}
          git push origin --delete ${{ inputs.branch-name }} || true
          git checkout -b ${{ inputs.branch-name }}
          git add .
          git commit -m "${{ inputs.commit-message}}"
          git push --set-upstream origin ${{ inputs.branch-name }}
          gh pr create -H ${{ inputs.branch-name }} -B ${{ inputs.base-branch }} --title 'Update ${{ inputs.target-path }}' --body 'Created by Github action' --label ${{ inputs.label}}
          cd ..
          rm -rf temp
      env: 
          GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
